# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"foo": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://hamelsmu.github.io/test-nbdev/"

git_url = "https://github.com/hamelsmu/test-nbdev/tree/master/"

def custom_doc_links(name): return None
